title:        JRN-418
tagline:      'Data Journalism at CCSU JRN-418, Fall 2015'
description:  'Data Journalism at CCSU, Fall 2015'
url:      http://localhost:4000/
version:      1.1.1
author:
  name:       ''
  email:      ''
markdown:     rdiscount
permalink:    pretty
pygments:     true
paginate:     5